### ISSUE TITLE
Remove blue horizontal line on "click" button at the bottom of the landing page view

### ISSUE THREAD

**Issue by arc9693** [lugnitdgp/Hack-Day-2019#104]
On hover, a blue horizontal line appears. Remove it.

**Comment by Idadelveloper** [comment]
Okay

**Comment by Thilagavathi1** [comment]
@arc9693 Removed and raise [PR](https://github.com/lugnitdgp/Hack-Day-2019/pull/120/commits/4806bebc298029522e266f5a12c5d18e0350abfd),Can you please check this.

**Comment by jyarali** [comment]
According to the HTML5 Spec Document from W3C, you can not nest a button inside an <a>.
This issue and nesting issue solved in #106
