### ISSUE TITLE
Remove yellow horizontal line on "Explore repositories" link and "Home" link

### ISSUE THREAD

**Issue by promaroy** [lugnitdgp/Hack-Day-2019#140]

**Comment by luucashc** [comment]
I do this!

**Comment by luucashc** [comment]
Done, i will do pull request.

**Comment by sapnatomar** [comment]
Hey, I have already made a pull request #146 . Please review it.

**Comment by CodeHacK3R** [comment]
Hi Proma.. can you plz review my pull request. I have improved the footer and it really looks good. Thanks.

**Comment by Str4nge** [comment]
I want to do this, how can I pull request?
